```{r}
library(ggplot2)
library(tidyverse)
library(MetBrewer)
library(sf)
library(rnaturalearth)
library(dplyr)
library(classInt) #install.packages('classInt')
library(ggspatial) #install.packages('ggspatial')
library(ggthemes) #install.packages('ggthemes')
library(tidymodels)
```

```{r}
# Read CA counties shapefile
ca_counties <- read_sf('../CA_Counties')
ca_counties <- ca_counties %>%
  st_transform(crs = "NAD83")
```
[109] "science_data_cds"                                                   
[110] "science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard"
[111] "science_data_Earth.and.Space.Sciences.Domain.Percent.Below.Standard"
[112] "science_data_Earth.and.Space.Sciences.Domain.Percent.Near.Standard" 
[113] "science_data_Grade"                                                 
[114] "science_data_Life.Sciences.Domain.Percent.Above.Standard"           
[115] "science_data_Life.Sciences.Domain.Percent.Below.Standard"           
[116] "science_data_Life.Sciences.Domain.Percent.Near.Standard"            
[117] "science_data_Mean.Scale.Score"                                      
[118] "science_data_Percentage.Standard.Exceeded"                          
[119] "science_data_Percentage.Standard.Met"                               
[120] "science_data_Percentage.Standard.Met.and.Above"                     
[121] "science_data_Percentage.Standard.Nearly.Met"                        
[122] "science_data_Percentage.Standard.Not.Met"                           
[123] "science_data_Physical.Sciences.Domain.Percent.Above.Standard"       
[124] "science_data_Physical.Sciences.Domain.Percent.Below.Standard"       
[125] "science_data_Physical.Sciences.Domain.Percent.Near.Standard"        
[126] "science_data_Student.Group.ID"                                      
[127] "science_data_Students.Enrolled"                                     
[128] "science_data_Students.Tested"                                       
[129] "science_data_Students.with.Scores"                                  
[130] "science_data_Test.ID"                                               
[131] "science_data_Test.Type"                                             
[132] "science_data_Test.Year"                                             
[133] "science_data_Total.Tested.at.Reporting.Level"                       
[134] "science_data_Total.Tested.with.Scores.at.Reporting.Level"           
[135] "science_data_Type.ID"

```{r}
school_map_sf <- merged_table %>%
  filter(!is.na(science_data_cds)) %>%
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = "NAD83")

ggplot() + 
  geom_sf(data=ca_counties) +
  geom_sf(data=school_map_sf, size=0.2) +
  theme_map() + 
  theme(legend.position = "right") 
```

 [77] "PE_data_cds"                                                        
 [78] "PE_data_CO"                                                         
 [79] "PE_data_DIST"                                                       
 [80] "PE_data_Line_Text"                                                  
 [81] "PE_data_NoHFZ5"                                                     
 [82] "PE_data_NoHFZ7"                                                     
 [83] "PE_data_NoHFZ9"                                                     
 [84] "PE_data_NoStud5"                                                    
 [85] "PE_data_NoStud7"                                                    
 [86] "PE_data_NoStud9"                                                    
 [87] "PE_data_Perc5a"                                                     
 [88] "PE_data_Perc5b"                                                     
 [89] "PE_data_Perc5c"                                                     
 [90] "PE_data_Perc7a"                                                     
 [91] "PE_data_Perc7b"                                                     
 [92] "PE_data_Perc7c"                                                     
 [93] "PE_data_Perc9a"                                                     
 [94] "PE_data_Perc9b"                                                     
 [95] "PE_data_Perc9c"                                                     
 [96] "PE_data_SCHL"
```{r}
school_map_sf <- merged_table %>%
  filter(!is.na(PE_data_cds)) %>%
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = "NAD83")

ggplot() + 
  geom_sf(data=ca_counties) +
  geom_sf(data=school_map_sf, size=0.2) +
  theme_map() + 
  theme(legend.position = "right") 
```

```{r}
school_map_sf <- wide_merged_data %>%
  filter(!is.na(growthscore_math)) %>%
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = "NAD83")

ggplot() + 
  geom_sf(data=ca_counties) +
  geom_sf(data=school_map_sf, size=0.2) +
  theme_map() + 
  theme(legend.position = "right") 
```

```{r}
merged_table %>%
  #filter(!is.na(PE_data_cds) & !is.na(science_data_cds)) %>%
  #filter(!is.na(PE_data_cds) | !is.na(science_data_cds)) %>%
  filter(xor(!is.na(PE_data_cds), !is.na(science_data_cds))) %>%
  distinct(CDSCode)

ls(merged_table)
```


```{r}
numeric <- merged_table %>%
  mutate(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard)) %>%
  mutate(science_data_Life.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Life.Sciences.Domain.Percent.Above.Standard)) %>%
  mutate(science_data_Physical.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Physical.Sciences.Domain.Percent.Above.Standard)) %>%
  mutate(PE_data_Perc5a = as.numeric(PE_data_Perc5a)) %>%
  mutate(PE_data_Perc7a = as.numeric(PE_data_Perc7a)) %>%
  mutate(PE_data_Perc9a = as.numeric(PE_data_Perc9a)) %>%
  mutate(enroll_raw = as.numeric(enroll_raw)) %>%
  mutate(pp_total_raw = as.numeric(pp_total_raw))
```

```{r}
lm_spec <- 
    linear_reg() %>% 
    set_engine(engine = 'lm') %>% 
    set_mode('regression')

mod1 <- fit(lm_spec, 
    ela_data_currstatus ~ science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard + PE_data_Perc5a + PE_data_Perc7a + PE_data_Perc9a + enroll_raw + pp_total_raw + Magnet, 
    data = numeric)

mod1 %>% tidy()
```
