---
title: "Beyond the Report Card: Our Motivation"
author: "Thu Dang, Nathaniel Reimer, Jeremy Hubinger"
bibliography: Library.bib
---

# A sneak peek into the data

The data set we have includes a range of school-related variables such as location details, funding, and aggregated scores in various subjects. Specifically, the score variables cover the general grade-cohort-standardized achievement score, as well as scores in reading, science, and physical education.

We aggregate our dataset from 5 different datasets. We use data from The California Department of Education, Georgetown University, and the Educational Opportunity Project at Stanford University.

**Science Testing Data** [Codebook](https://github.com/JeremyHub/STAT-456-Final/blob/8ef6fa6ce28785065f583f4c477c5deb11afd442/final_project_stuff/science_docs.pdf)

Our science test data is from the California Department of Education, specifically, from the 2021-2022 school year. It is from the California Science Test, in which there are three different categories, namely Life sciences, Physical sciences, and Earth and Space sciences.

**English Testing Data** [Codebook](https://github.com/JeremyHub/STAT-456-Final/blob/8ef6fa6ce28785065f583f4c477c5deb11afd442/final_project_stuff/ela_docs.pdf)

The data we have for English Language Arts / Literature is also from the California Department of Education, specifically from 2022. It tells us for each student group within each school their level of proficiency.

**Physical Education Data**

Our PE data comes from the California Department Education from the 2018-2019 school year. It has 7 different types of exercises and each school's grade's proficiency on each type of exercise.

**School Funding Data** [Codebook](https://github.com/JeremyHub/STAT-456-Final/blob/8ef6fa6ce28785065f583f4c477c5deb11afd442/final_project_stuff/school_info_docs.pdf)

Our school funding data is aggregated 2019-2020 data from different federal and state sources. It is compiled into the dataset we are using by Georgetown University researchers. It has information about funding going to a school from the state, local, and federal governments, as well as metadata about the school such as enrollment, as well as data about the income levels of the students at the school.

**The Educational Opportunity Project at Stanford University (SEDA)** [Codebook](https://github.com/JeremyHub/STAT-456-Final/blob/82e84dd90db010d96edba2d74dc574c15648a10c/final_project_stuff/stanford_codebook.xlsx) [Covariate Codebook](https://github.com/JeremyHub/STAT-456-Final/blob/82e84dd90db010d96edba2d74dc574c15648a10c/final_project_stuff/stanford_cov_codebook.xlsx)

The SEDA dataset contains school-level standardized academic achievement data across all Californian schools. These achievement scores are graded and cohort standardized against the NAEP standard, indicating whether the students in a particular school and grade level are meeting the national standard for their grade. For instance, if a school's 4th-grade students score 3.5, it indicates that they are lagging behind the national standard by 0.5 points. The achievement estimates are calculated using Ordinary Least Square (OLS) and Empirical Bayesian (EB) techniques.

**School Details**

This contains metadata on 10629 California Schools. Including both the nationally used NCES id and the California CDS code. We use this to join our data from our different sources. This dataset also contains the longitude and latitude of the schools which has been very useful for EDA so far.

**Aggregated Growth**  
[Codebook](https://www.cde.ca.gov/ta/ac/growthreclayout.asp)  
This contains data on Mathematics and English Language Arts growth by school and student group for California Schools. California developed the growth model to show how much student's scores were growing from year to year. 

# Going into details regarding the metrics considered in this analysis

In this analysis, we focused on using Grade Cohort Standardized scores, which is a metric created by the SEDA project, and growth score (?), both at county- and school-level. Additionally, we also considered school-level test scores in various subjects, including English, Science, and Physical Education (PE).

**Grade Cohort Standardized (GCS) scores**: According to the Stanford Codebook, "\[t\]he GCS scale standardizes the unit means relative to the average difference in NAEP scores between students one grade level apart" [@seda_methods]. NAEP stands for National Assessment of Educational Progress, which is an assessment program in the United States that aiming to assess and measure the academic performance of students across different subjects and grades, generally referred to as the Nation's Report Card [@naep_definition]. The GCS scale allows users to understand one unit as being equivalent to one grade level. In Grade 3, the national average performance is 3 units, while in Grade 4, it is 4 units, and so on. Here are two brief examples to interpreting GCS values: If 4th-grade students at the school of interest have a GCS value of 5.03, these students' scores indicate a level equivalent to 5th-grade, which is about one grade level higher than the national average (the reference group) in math. Vice versa, if 3rd-grade students at the school of interest have a GCS value of 2.39, these students' reading scores indicate a level about half a grade level lower than the national average for 3rd-grade students [@seda_methods]. GCS values are aggregated over years and are collected at school- and county-level.

**Growth score**: Aggregate growth scores are available for English and Mathematics broken down by school and student group. They measure how close the students growth is to their expected growth. A growth score of 100 indicates students are meeting expected growth; below 100 indicates growth below expectations; and above 100 indicates growth above expectations. Since the scores measure growth they are based on multiple years of testing data: the 2016-17, 2017-18, and 2018-19 school years. Pandemic disruption means that the current growth scores are not actionable. Growth scores will be released again in 2024. Nevertheless, the scores are still useful for our analysis.

**Subject-specific test scores**: We obtained data on test scores for various subjects, including English, Science, and PE. During our initial investigation, after joining these test score datasets with the SEDA and funding data, we saw that the test scores only matched up with a very small percentage of schools in our dataset. Further investigation shows that the test scores are only collected in the East Bay area and various northern CA counties. Since it is desirable to have a full coverage of state scores for the subsequent analysis and modeling process, we decided not to use the subject-specific test score datasets.

We can add that interesting viz here -- what interesting viz?
