---
title: "Beyond the Report Card: Our Motivation"
author: "Thu Dang, Nathaniel Reimer, Jeremy Hubinger"
bibliography: Library.bib
---

# A change in direction

Initially, we focused on the correlation between affordable housing and educational achievement. However, while selecting appropriate achievement proxies, we found ourselves delving into the factors behind the measurements of these proxies. As a result, we decided to seek the guidance of Professor Lesley Lavery, who specializes in public policies in education. We hope to better understand the educational proxies currently in use and investigate whether there are additional factors that impact educational outcomes and potentially render the current proxies interchangeable or distinct from other measures.

# Previous literature

There are several reasons why education proxies differ, including the influence of socioeconomic status, the difficulty in standardizing scores across schools, and variations in school budgets. While % of high school graduates may be a more robust metric to estimate the education achievement level in different areas, it is harder to standardize score-related metrics due to differences in grading scales and the difficulty of obtaining student-level data [@expert_interview].

Additionally, due to the diverse student body in the US, it is difficult to identify specific teaching approaches that are effective for particular groups of students. The Measures of Effective Teaching Project by the Gates Foundation aimed to establish innovative teacher-evaluation systems incorporating classroom observation rubrics and student achievement growth measures. Although the Gates Foundation allocated \$600 million towards this initiative, it turned out to be a challenging task, particularly in identifying effective teaching elements that positively influence students' academic performance. Consequently, this research heightened our curiosity in examining other factors that contribute to students' achievements beyond teaching approaches [@gates_foundation].

Another discourse associated with academic achievement is how funding is allocated for education and whether spending more helps improve academic achievement. Funding disparities remain significant on a national level. Districts with the highest poverty rates in the country receive approximately \$1,000 less per student compared to those with the lowest poverty rates. The difference is almost double, around \$1,800 less per student, for districts serving the highest number of students of color versus those serving the lowest. However, there's variation in state trend: While certain states allocate considerably more funding to their most impoverished districts, others provide notably less. Furthermore, when the researchers took into account that students living in poverty require extra support to excel academically, the funding differences between high and low-poverty districts appear even more severe. This indicates that merely providing equal funding is insufficient [@money_edtrust]. This is a great insight that motivates us to look further into funding and the associated factors that can potentially confound funding in our analysis.

# Why California?

Various socioeconomic factors can affect students' academic performance beyond teaching methods. California is a diverse state with people from different socioeconomic backgrounds, it presents an intriguing case study for our research topic, which focuses on exploring the socioeconomic factors that influence students' grades.
