---
title: "Beyond the Report Card: Let's discuss some results!"
author: "Thu Dang, Nathaniel Reimer, Jeremy Hubinger"
execute: 
  echo: false
  warning: false
  message: false
bibliography: Library.bib
---

# What did we find, and what do they mean?

There is a high degree of variation in the county and school-level achievement data. Wealthier counties and counties with large urban areas see higher average student achievement. When we separate economically disadvantaged and non-economically disadvantaged students the economically disadvantaged students have lower average achievement in math and english. At the school level there is more significant variability. High-achieving and low-achieving schools can be found close to each other, but there are many groups of high and low-achieving schools. 

Diving deeper into school funding, we find that schools with a higher proportion of disadvantaged students often have more funding than schools with fewer disadvantaged students which may be misleading at first glance. When we account for the greater need of these economically disadvantaged students, disadvantaged schools appear to be underfunded. One of the explanations for this result is that it requires more funding to serve schools where poverty is concentrated. California is a relatively diverse state, and with a history of redlining, school segregation is inevitable. Therefore, underprivileged students tend to be concentrated in certain areas. Although schools with a high proportion of economically disadvantaged students receive more funding, the majority of the funding goes to supporting students' welfare, that is, special education, free/reduced lunch programs, as well as human capital costs like teachers' salaries and health services. Therefore, little is left to support students academically [@school_segregation; @teacher_inflation; @expert_interview]. Funding schools equally is not an equitable or effective solution to bridge the gap in socioeconomic status; there are still gaps in academic achievement left unbridged. 

From our LASSO graphs and the models we created we compare the differences between GCS and growth scores. We saw that GCS was heavily correlated with factors out of control of a school such as the percentage of their students who are economically disadvantaged. If we were to use this metric as a proxy for educational outcome, a lot of what we would be measuring would be inalienable factors about the students rather than how well the school is doing teaching their kids.

Finally, after modeling our data with LASSO, it seems for the schools we are investigating, growth score did not have any predictors that were able to account for a significant amount of the variation we saw across schools. In other words, if we were to use growth scores as a proxy for educational outcome we would not be measuring these inalienable factors that GCS measures. If we want a way to distinguish between schools that are doing the best they can and schools that could be doing better with the resources they have then this is a good thing. Growth score is a relatively unbiased proxy to measure students' achievement regardless of their socioeconomic status and the schools' funding status.

# Limitations and moving forward

There are some limitations in our project. We have excluded observations with incomplete data. Due to time constraints, we could only focus on employing LASSO for modeling purposes. We have to exclude a few datasets due to coverage problem, meaning that the data is only collected in certain counties north of CA and could potentially induce bias had we used them. 

There are some improvements that we would love to make in our project: 

- We recognize there are differences in socioeconomic factors and educational measures among various states. Since we only focus on California, we would love to analyze data in other states to investigate more general trends.

- We want to deal with missing data using spatial models instead of just dropping the observations since there might be spatial correlation in the data. 

- As some of the datasets we obtained contain observations over multiple years, it would be beneficial to conduct time series analysis to explain trends and patterns over time.

- In this analysis, since we gain various insights from our expert, Prof. Lesley Lavery, we would love to find and talk with more local experts for more context to dive deeper into our results.

- We think it is interesting to explore other modeling techniques, that is, hierarchical linear model as suggested by our expert, or look at possible nonlinearity.

- Last but not least, we hope to obtain more data with better state coverage, that is, data collected from across the state of interest rather than being limited to a small number of counties within the state.

# On ethics

To ensure privacy concerns are addressed, we take measures to aggregate the data at the school level. However, we recognize that there may be potential issues with bias in the data collection process and data accuracy as a result.

Regarding potential bias, the data is taken from various sources, and it is possible that each school may have different processes for collecting the data. With the exception of the Educational Opportunity Project at Stanford University, we do not have information on the number of students for whom the data is collected, nor the demographic makeup of those students. As a result, we acknowledge that there may be inherent biases in the data that we cannot control due to a lack of information.

Regarding data accuracy, as we do not have detailed documentation for all of the datasets, it is challenging to ascertain their accuracy. However, we have confidence in the reliability of the government and highly-credited sources from which the data originates. Given this, we consider these datasets to be our most reliable option at present.

Taken out of context, our analyses and graphics have the potential to negatively impact educational policy. Particularly since we will be looking at demographics and funding data. We need to be careful and deliberate in our analysis to minimize harm.


