---
title: "Beyond the Report Card: What are the insights at the school level that we can observe?"
author: "Thu Dang, Nathaniel Reimer, Jeremy Hubinger"
execute: 
  echo: false
  warning: false
  message: false
---

```{r packages}
library(tidyverse)
library(MetBrewer)
library(sf)
library(rnaturalearth)
library(classInt) #install.packages('classInt')
library(ggspatial) #install.packages('ggspatial')
library(ggthemes) #install.packages('ggthemes')
library(RColorBrewer)
library(patchwork)
library(leaflet)
library(probably) #install.packages('probably')
library(glmnet)
library(tidymodels)
tidymodels_prefer()
```

```{r color}
palname = "Homer2"
defaultcolor = met.brewer(palname,10)[9]
```

```{r load datasets}
load("CombinedDataLongFormat.RData")
load("WideMergedData.RData")
```

```{r load cleaned dataset for county achievement metrics}
math_ca_gcs_df <- read_csv("AllDatasets/math_ca_gcs_df.csv")
rla_ca_gcs_df <- read_csv("AllDatasets/rla_ca_gcs_df.csv")
```

```{r maps load shapefile}
ca_counties <- read_sf('CA_Counties')
ca_counties <- ca_counties %>%
  st_transform(crs = "NAD83")
```

## Map of School-level academic achievement categories across California counties

```{r funding/performance map}
mapdata <- wide_merged_data %>% filter(!is.na(gradecenter)&!is.na(gcs_mn_avg_ol)) %>% 
  mutate(diff_from_gradecenter = gcs_mn_avg_ol - gradecenter, pp_total_raw = as.numeric(pp_total_raw)) %>%
  mutate(Longitude = as.numeric(Longitude), Latitude = as.numeric(Latitude)) %>%
  mutate(pp_total_raw_cat = cut(pp_total_raw, breaks = c(0,10000,15000,20000,Inf))) %>%
  mutate(diff_from_gradecenter_cat = cut(diff_from_gradecenter, breaks = c(-Inf, -3, -1, 1, 3, Inf)))

p1 <- colorFactor(
  palette = met.brewer(palname, 5)[1:5],
  domain = mapdata$diff_from_gradecenter_cat
)

pal <- colorFactor(
  palette = met.brewer(palname, 4)[1:4],
  domain = mapdata$pp_total_raw_cat
)

leaflet(mapdata) %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    color = ~p1(diff_from_gradecenter_cat),
    radius = ~(as.numeric(ncesenroll)/400),
    popup = ~paste0(School, 
                    "<br>Grade Distance from National Average: ", round(diff_from_gradecenter, digits = 3),
                    "<br>Per Pupil Funding: ", pp_total_raw,
                    "<br>Enrollment: ", ncesenroll
    ),
    group = "Performance"
  ) %>% 
  addLegend(position = "bottomright", colors = met.brewer(palname, 5)[1:5], title = "Performance", labels = c("3+ years behind", "1-3 years behind",  "Within 1 year of national average",  "1-3 years ahead", "3+ years ahead"))



leaflet(mapdata) %>% addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    color = ~pal(pp_total_raw_cat),
    radius = ~(as.numeric(ncesenroll)/400),
    popup = ~paste0(School, 
                    "<br>Grade Distance from National Average: ", round(diff_from_gradecenter, digits = 3),
                    "<br>Per Pupil Funding: ", pp_total_raw,
                    "<br>Enrollment: ", ncesenroll
    ),
    stroke = ~ifelse(!is.na(pp_total_raw_cat), TRUE, FALSE),
    group = "Funding"
  ) %>%
addLegend("bottomright", colors = met.brewer(palname, 4)[1:4], title = "Per Student Funding", labels = c("$10,000 or less", "$10,000 to $15,000", "15,000 to 20,000", "Greater than 20,000")) 
```

## Does funding impact school-level academic achievement?

```{r funding and performance by area}
wide_merged_data %>% filter(!is.na(urbanicity)) %>%
  ggplot(aes(x=as.numeric(pp_total_raw), y=(as.numeric(gcs_mn_avg_ol)-as.numeric(gradecenter)))) +
  geom_point(alpha = .1, color=defaultcolor) + 
  geom_smooth(method = lm, color=defaultcolor) + 
  facet_wrap(~urbanicity) + 
  scale_x_continuous(limits = c(8000,18000)) + 
  theme_minimal()+
  labs(y="Grade Cohort Score", x= "Unadjusted Per Student Spending") + guides(color="none") +   geom_hline(yintercept = 0)
```

```{r funding model, results='hide'}
#| message: true
fundingmod<-wide_merged_data %>% 
  filter(!is.na(pp_total_raw)&!is.na(perfrl)) %>% 
  lm(formula = as.numeric(pp_total_raw) ~ as.numeric(perfrl) + 
       as.numeric(lep_flag) + 
       as.numeric(perfrl)*as.numeric(lep_flag)) %>%
  summary()

lunchfundingmod<-wide_merged_data %>% 
  filter(!is.na(pp_total_raw)&!is.na(perfrl)) %>% 
  lm(formula = as.numeric(pp_total_raw) ~ as.numeric(perfrl)) %>%
  summary()

# fundingmod$coefficients
lunchfundingmod$coefficients
```


```{r area adjusted graph}
wide_merged_data %>% filter(!is.na(urbanicity)) %>% mutate(pp_total_raw_frl_adjusted = as.numeric(pp_total_raw) - as.numeric(perfrl)*lunchfundingmod$coefficients[2],
  pp_total_raw = as.numeric(pp_total_raw)) %>%
  ggplot(aes(x=as.numeric(pp_total_raw_frl_adjusted), y=(as.numeric(gcs_mn_avg_ol)-as.numeric(gradecenter)))) +
  geom_point(alpha = .1, color=defaultcolor) + 
  geom_smooth(method = lm, color=defaultcolor) + 
  facet_wrap(~urbanicity) + 
  scale_x_continuous(limits = c(8000,18000)) + 
  theme_minimal()+
  labs(y="Grade Cohort Score", x= "Adjusted Per Student Spending") + guides(color="none") +   geom_hline(yintercept = 0)
```


