---
title: "California School EDA"
output:
  pdf_document: default
  html_document: default
date: "`r Sys.Date()`"
---
```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(MetBrewer)
```

```{r data, message=FALSE, warning=FALSE, include=FALSE}
wideschooldata21 <- read.csv("wideschooldata.csv")
schoolsummary <- read.csv("schoolsummary.csv")
wideschooldata21_19 <- wideschooldata21 %>% select(-X) %>% full_join(schoolsummary)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
theme_nr <- function(){
  font <- "AvantGarde"
  theme_minimal() %+replace%
  theme(
    panel.grid = element_blank(),
    
    axis.ticks = element_line(),
    
    plot.title = element_text(
      family = font,
      size = 14,
      hjust = 0
    ),
    plot.subtitle = element_text(
      family = font,
      size = 10,
      hjust = 0
    ),
    plot.caption = element_text(
      family = font,
      size = 8,
      hjust = 1
    ),
    axis.title = element_text(
      family = font,
      size = 10
    ),
    axis.text = element_text(
      family = font,
      size = 8
    )
  )
}
```


```{r echo=FALSE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE}
wideschooldata21_19 %>% filter(GRADE=="00", CATEGORY=="ALL", flag_nerds == FALSE) %>%
  ggplot() +
    geom_point(aes(y=MTH_PCTPROF_max,x=ELA_PCTPROF_max, color=CATEGORY), alpha=.2)  + geom_abline(slope = 1,intercept = 0) +
    labs(x="Max ELA Proficiency by School", y="Max Math Proficiency by School",title = "Underperformance on Mathematics Exams") + theme_nr() + scale_color_met_d("Juarez",direction = 1) + guides(color=FALSE)
```
```{r echo=FALSE, fig.height=4, fig.width=8, message=FALSE, warning=FALSE}
fl<-c("Male","Female")
names(fl)<-c("M","F")
wideschooldata21_19 %>% filter(GRADE=="00", flag_nerds == FALSE, CATEGORY %in% c("M","F")) %>%
  ggplot() +
    geom_point(aes(y=MTH_PCTPROF_max,x=ELA_PCTPROF_max,color=CATEGORY), alpha=.2)  + geom_abline(slope = 1,intercept = 0) +
    labs(x="Max ELA Proficiency by School", y="Max Math Proficiency by School",title = "Variation in Underperformance in Mathematics Exams",) +
    facet_wrap(~CATEGORY, labeller = labeller(CATEGORY=fl)) + theme_nr() + scale_color_met_d("Juarez",direction = 1) + guides(color=FALSE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=6, fig.width=6}
fl<-c("English Language Arts","Mathematics")
names(fl)<-c("ELA_PCTPROF_max","MTH_PCTPROF_max")
wideschooldata21_19 %>% mutate(enroll_raw = as.numeric(enroll_raw)) %>% mutate(enroll_cat = cut(enroll_raw,breaks = c(0,500,1000,8000),labels = c("Small (<500)","Medium (500-1000)","Large (>1000)"))) %>% filter(GRADE=="00", flag_nerds == FALSE, CATEGORY %in% c("ALL","MBL")) %>% select(MTH_PCTPROF_max,MTH_PCTPROF_min,ELA_PCTPROF_max,ELA_PCTPROF_min,enroll_cat,pp_total_norm_NERDS) %>% pivot_longer(cols = contains("PCTPROF_max")) %>%
  ggplot(aes(y=value,x=as.numeric(pp_total_norm_NERDS),color=enroll_cat)) +
    geom_point(alpha=.2) + scale_x_continuous(limits=c(5000,30000)) + geom_smooth(method = lm,se=FALSE) + labs(x="Spending per Student",y="Max Proficiency",title = "Spending and Student Performance",color="School Size") + facet_grid(rows = vars(name),labeller = labeller(name=fl)) +scale_color_met_d("Juarez",direction = -1) + theme_nr()
```



