```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
min_max_norm <- function(x) {
    (x - min(x, na.rm=TRUE)) / (max(x, na.rm=TRUE) - min(x, na.rm=TRUE))
}

# model metrics by per pupil funding
grouped_merged_table <- merged_table %>%
  filter(flag_nerds == 'false' || is.na(flag_nerds)) %>%
  filter(flag_f33 != '1' || is.na(flag_f33)) %>%
  mutate(pp_total_raw = as.numeric(pp_total_raw))%>%
  filter(pp_total_raw < 100000) %>% #filters 1 school out
  # mutate to then as.numeric
  mutate(
      science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard),
      science_data_Physical.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Physical.Sciences.Domain.Percent.Above.Standard),
      science_data_Life.Sciences.Domain.Percent.Above.Standard = as.numeric(science_data_Life.Sciences.Domain.Percent.Above.Standard),
      ela_data_currstatus = as.numeric(ela_data_currstatus),
      gcs_mn_avg_ol = as.numeric(gcs_mn_avg_ol)
  ) %>%
  mutate(ela_data_currstatus = ela_data_currstatus * ela_data_currdenom) %>%
  group_by(CDSCode, pp_total_raw, Latitude, Longitude) %>%
  summarise(
    science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard = mean(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard, na.rm = TRUE),
    science_data_Physical.Sciences.Domain.Percent.Above.Standard = mean(science_data_Physical.Sciences.Domain.Percent.Above.Standard, na.rm = TRUE),
    science_data_Life.Sciences.Domain.Percent.Above.Standard = mean(science_data_Life.Sciences.Domain.Percent.Above.Standard, na.rm = TRUE),
    ela_data_currstatus = mean(ela_data_currstatus, na.rm = TRUE),
    gcs_mn_avg_ol = mean(gcs_mn_avg_ol, na.rm = TRUE),
  ) %>%
  ungroup()

graph_ready <- grouped_merged_table %>%
  na.omit() %>% #only looking at the same schools. this line is doing a lot though
  filter(pp_total_raw < 20000) %>% # removes 2 schools
  # normalize the metrics
    mutate(
        science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard = min_max_norm(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard),
        science_data_Physical.Sciences.Domain.Percent.Above.Standard = min_max_norm(science_data_Physical.Sciences.Domain.Percent.Above.Standard),
        science_data_Life.Sciences.Domain.Percent.Above.Standard = min_max_norm(science_data_Life.Sciences.Domain.Percent.Above.Standard),
        ela_data_currstatus = min_max_norm(ela_data_currstatus),
        gcs_mn_avg_ol = min_max_norm(gcs_mn_avg_ol)
    ) %>%
  group_by(CDSCode) %>%
  pivot_longer(cols=c(science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard,science_data_Physical.Sciences.Domain.Percent.Above.Standard,science_data_Life.Sciences.Domain.Percent.Above.Standard,ela_data_currstatus,gcs_mn_avg_ol))
```

```{r}
fl <- c("English Language Arts", "Grade Cohort Standardized", "Earth + Space", "Life Sciences", "Physical Sciences")
names(fl) <- c("ela_data_currstatus", "gcs_mn_avg_ol", "science_data_Earth.and.Space.Sciences.Domain.Percent.Above.Standard", "science_data_Life.Sciences.Domain.Percent.Above.Standard", "science_data_Physical.Sciences.Domain.Percent.Above.Standard")
graph_ready %>%
  ggplot(aes(color = name, y = Latitude, x = Longitude, color=value/pp_total_raw)) +
  geom_point(alpha=0.3)+
  facet_wrap(~name, labeller=labeller(name=fl))+
  geom_smooth()+
  labs(x = "Per Pupil Funding", y = "Normalized Metric", title = "Metric Performance by Total Per-Pupil Funding") +
  theme_bw() +
  theme(
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.position = "none"
  )
```
```{r}
ls(merged_table)
merged_table %>%
  select(enroll_raw, schooltot_raw, gradespan) %>%
  na.omit() %>%
  group_by(gradespan) %>%
  count() %>%
  left_join(merged_table) %>%
  select(enroll_raw, schooltot_raw, gradespan, n) %>%
  na.omit() %>%
  filter(n > 1000) %>%
  ggplot(aes(x=enroll_raw, y=schooltot_raw)) +
  geom_point() +
  facet_wrap(~gradespan)
```


